import { db } from '../index.js';
import {
  inventoryAdjustments,
  inventoryAdjustmentLines,
  inventoryLevels,
  inventoryLedgers,
} from '../schema/index.js';
import { SEED_DATA } from './constants.js';
import { eq, sql } from 'drizzle-orm';
import { subDays } from 'date-fns';

/**
 * Seeds the opening inventory state for the ERP.
 *
 * ARCHITECTURE NOTE — Stock Safety Budget:
 * The scenario engine (scenarios.seed.ts) runs 39 O2C shipments cycling across
 * all active products. Each shipment can consume up to 15 units. With ~4 shipments
 * per product at max 15 units = 60 units per product from MAIN warehouse's MAIN_A1 bin.
 * Opening stock is set well above this threshold to prevent Postgres' qty_on_hand >= 0
 * check constraint from firing during the scenario seeding phase.
 *
 * LEDGER STRATEGY:
 * This file creates 'adjustment' type entries only — the 'po_receipt' and 'so_shipment'
 * entries are generated by the purchasing/sales factories when scenarios run.
 * Together they form a rich, realistic ledger history.
 */

export async function seedInventory() {
  console.log('🌱 Seeding Inventory Adjustments & Levels...');

  const now = new Date();

  const adjustments = [
    /**
     * ADJUSTMENT 1: Opening stock — Main Warehouse
     * Represents the initial physical stock count on Day 0 of operations.
     * Back-dated 60 days so all subsequent scenario transactions sit in the
     * correct chronological position in the ledger.
     */
    {
      id: SEED_DATA.INVENTORY_ADJUSTMENTS.INITIAL_STOCK,
      reference: 'ADJ-OPEN-MAIN-001',
      reason: 'Opening Stock Load — Main Warehouse',
      date: subDays(now, 60),
      lines: [
        {
          productId: SEED_DATA.PRODUCTS.WIDGET_A,
          warehouseId: SEED_DATA.WAREHOUSES.MAIN,
          binId: SEED_DATA.BINS.MAIN_A1,
          quantity: '500',
        },
        {
          productId: SEED_DATA.PRODUCTS.WIDGET_B,
          warehouseId: SEED_DATA.WAREHOUSES.MAIN,
          binId: SEED_DATA.BINS.MAIN_B1,
          quantity: '600',
        },
        {
          productId: SEED_DATA.PRODUCTS.STEEL_SHEET,
          warehouseId: SEED_DATA.WAREHOUSES.MAIN,
          binId: SEED_DATA.BINS.MAIN_A1,
          quantity: '300',
        },
        {
          productId: SEED_DATA.PRODUCTS.COPPER_WIRE,
          warehouseId: SEED_DATA.WAREHOUSES.MAIN,
          binId: SEED_DATA.BINS.MAIN_B1,
          quantity: '400',
        },
        {
          productId: SEED_DATA.PRODUCTS.OFFICE_PAPER,
          warehouseId: SEED_DATA.WAREHOUSES.MAIN,
          binId: SEED_DATA.BINS.MAIN_A1,
          quantity: '350',
        },
        {
          productId: SEED_DATA.PRODUCTS.INK_CARTRIDGE,
          warehouseId: SEED_DATA.WAREHOUSES.MAIN,
          binId: SEED_DATA.BINS.MAIN_B1,
          quantity: '250',
        },
        {
          productId: SEED_DATA.PRODUCTS.PACKAGING_BOX,
          warehouseId: SEED_DATA.WAREHOUSES.MAIN,
          binId: SEED_DATA.BINS.MAIN_A1,
          quantity: '800',
        },
        {
          productId: SEED_DATA.PRODUCTS.ASSEMBLY_KIT,
          warehouseId: SEED_DATA.WAREHOUSES.MAIN,
          binId: SEED_DATA.BINS.MAIN_B1,
          quantity: '150',
        },
      ],
    },

    /**
     * ADJUSTMENT 2: Opening stock — Distribution Center
     * High-value components and electronics live in the DC's high-bay racks.
     * These are primarily sourced via POs and shipped out as finished goods.
     */
    {
      id: SEED_DATA.INVENTORY_ADJUSTMENTS.INITIAL_STOCK_DC,
      reference: 'ADJ-OPEN-DC-001',
      reason: 'Opening Stock Load — Distribution Center',
      date: subDays(now, 60),
      lines: [
        {
          productId: SEED_DATA.PRODUCTS.MICROCHIP_X,
          warehouseId: SEED_DATA.WAREHOUSES.DIST_CENTER,
          binId: SEED_DATA.BINS.DC_RACK_1,
          quantity: '2000',
        },
        {
          productId: SEED_DATA.PRODUCTS.LED_DISPLAY,
          warehouseId: SEED_DATA.WAREHOUSES.DIST_CENTER,
          binId: SEED_DATA.BINS.DC_RACK_2,
          quantity: '1200',
        },
        {
          productId: SEED_DATA.PRODUCTS.WIDGET_A,
          warehouseId: SEED_DATA.WAREHOUSES.DIST_CENTER,
          binId: SEED_DATA.BINS.DC_RACK_1,
          quantity: '300',
        },
        {
          productId: SEED_DATA.PRODUCTS.COPPER_WIRE,
          warehouseId: SEED_DATA.WAREHOUSES.DIST_CENTER,
          binId: SEED_DATA.BINS.DC_RACK_2,
          quantity: '200',
        },
      ],
    },

    /**
     * ADJUSTMENT 3: Enrichment — Low-stock signal items
     * These are intentionally seeded with low quantities so the inventory
     * dashboard can display "low stock" warning indicators.
     */
    {
      id: SEED_DATA.INVENTORY_ADJUSTMENTS.ENRICHMENT_STOCK,
      reference: 'ADJ-ENRICH-001',
      reason: 'Enrichment — Low Stock Alert Items',
      date: subDays(now, 55),
      lines: [
        {
          productId: SEED_DATA.PRODUCTS.INK_CARTRIDGE,
          warehouseId: SEED_DATA.WAREHOUSES.DIST_CENTER,
          binId: SEED_DATA.BINS.DC_RACK_1,
          quantity: '6',
        },
        {
          productId: SEED_DATA.PRODUCTS.PACKAGING_BOX,
          warehouseId: SEED_DATA.WAREHOUSES.SECONDARY,
          binId: SEED_DATA.BINS.SEC_RACK_1,
          quantity: '12',
        },
        {
          productId: SEED_DATA.PRODUCTS.ASSEMBLY_KIT,
          warehouseId: SEED_DATA.WAREHOUSES.DIST_CENTER,
          binId: SEED_DATA.BINS.DC_RACK_2,
          quantity: '8',
        },
      ],
    },

    /**
     * ADJUSTMENT 4: Damage write-off — Q1 Cycle Count
     * Negative adjustment representing goods damaged during Q1 storage audit.
     * Demonstrates the 'adjustment' ledger type with negative quantity changes,
     * which is critical for testing the UI's green/red quantity rendering logic.
     */
    {
      id: SEED_DATA.INVENTORY_ADJUSTMENTS.DAMAGE_WRITEOFF,
      reference: 'ADJ-DMGWRIT-Q1-001',
      reason: 'Damage Write-off — Q1 Physical Count Variance',
      date: subDays(now, 45),
      lines: [
        {
          productId: SEED_DATA.PRODUCTS.WIDGET_A,
          warehouseId: SEED_DATA.WAREHOUSES.MAIN,
          binId: SEED_DATA.BINS.MAIN_A1,
          quantity: '-12', // 12 units found damaged/unusable
        },
        {
          productId: SEED_DATA.PRODUCTS.STEEL_SHEET,
          warehouseId: SEED_DATA.WAREHOUSES.MAIN,
          binId: SEED_DATA.BINS.MAIN_A1,
          quantity: '-5', // 5 sheets warped/corroded
        },
        {
          productId: SEED_DATA.PRODUCTS.PACKAGING_BOX,
          warehouseId: SEED_DATA.WAREHOUSES.MAIN,
          binId: SEED_DATA.BINS.MAIN_A1,
          quantity: '-30', // 30 boxes crushed in storage
        },
      ],
    },

    /**
     * ADJUSTMENT 5: Annual cycle count variance
     * Mixed positive and negative adjustments from a full physical inventory count.
     * Some bins had more than the system showed (positive variance), some had less.
     * This is the most realistic "real world" adjustment scenario for an ERP demo.
     */
    {
      id: SEED_DATA.INVENTORY_ADJUSTMENTS.CYCLE_COUNT_VARIANCE,
      reference: 'ADJ-CYCLECOUNT-ANN-001',
      reason: 'Annual Cycle Count — Stock Reconciliation',
      date: subDays(now, 30),
      lines: [
        {
          productId: SEED_DATA.PRODUCTS.COPPER_WIRE,
          warehouseId: SEED_DATA.WAREHOUSES.MAIN,
          binId: SEED_DATA.BINS.MAIN_B1,
          quantity: '+8', // Found 8 extra units not in system
        },
        {
          productId: SEED_DATA.PRODUCTS.OFFICE_PAPER,
          warehouseId: SEED_DATA.WAREHOUSES.MAIN,
          binId: SEED_DATA.BINS.MAIN_A1,
          quantity: '-15', // 15 boxes missing — assumed consumed without recording
        },
        {
          productId: SEED_DATA.PRODUCTS.LED_DISPLAY,
          warehouseId: SEED_DATA.WAREHOUSES.DIST_CENTER,
          binId: SEED_DATA.BINS.DC_RACK_2,
          quantity: '-3', // 3 units unaccounted for
        },
        {
          productId: SEED_DATA.PRODUCTS.MICROCHIP_X,
          warehouseId: SEED_DATA.WAREHOUSES.DIST_CENTER,
          binId: SEED_DATA.BINS.DC_RACK_1,
          quantity: '+20', // 20 extra chips found in unlabelled tray
        },
      ],
    },

    /**
     * ADJUSTMENT 6: Inter-warehouse transfer — Main → Secondary (Outbound leg)
     * Represents a deliberate stock rebalancing between warehouses.
     * This is modelled as two separate adjustments (outbound + inbound) because
     * the schema does not yet have a dedicated 'transfer' transaction type.
     *
     * NOTE: The 'transfer' referenceType exists in the inventoryReferenceTypeEnum
     * but there is no inventory transfer module yet. Using 'adjustment' is the
     * correct interim approach — this is explicitly documented for future migration.
     */
    {
      id: SEED_DATA.INVENTORY_ADJUSTMENTS.TRANSFER_MAIN_TO_SEC,
      reference: 'ADJ-XFER-MAIN-SEC-001-OUT',
      reason: 'Inter-Warehouse Transfer (Outbound) — Main → Secondary Storage',
      date: subDays(now, 15),
      lines: [
        {
          productId: SEED_DATA.PRODUCTS.WIDGET_B,
          warehouseId: SEED_DATA.WAREHOUSES.MAIN,
          binId: SEED_DATA.BINS.MAIN_B1,
          quantity: '-50', // Outbound from Main
        },
        {
          productId: SEED_DATA.PRODUCTS.OFFICE_PAPER,
          warehouseId: SEED_DATA.WAREHOUSES.MAIN,
          binId: SEED_DATA.BINS.MAIN_A1,
          quantity: '-100', // Outbound from Main
        },
      ],
    },

    /**
     * ADJUSTMENT 7: Inter-warehouse transfer — Main → Secondary (Inbound leg)
     * The inbound receipt at the Secondary warehouse, completing the stock transfer.
     * Same timestamp as the outbound to represent an atomic transfer event.
     */
    {
      id: SEED_DATA.INVENTORY_ADJUSTMENTS.TRANSFER_MAIN_TO_SEC_INBOUND,
      reference: 'ADJ-XFER-MAIN-SEC-001-IN',
      reason: 'Inter-Warehouse Transfer (Inbound) — Main → Secondary Storage',
      date: subDays(now, 15),
      lines: [
        {
          productId: SEED_DATA.PRODUCTS.WIDGET_B,
          warehouseId: SEED_DATA.WAREHOUSES.SECONDARY,
          binId: SEED_DATA.BINS.SEC_RACK_1,
          quantity: '50', // Received at Secondary
        },
        {
          productId: SEED_DATA.PRODUCTS.OFFICE_PAPER,
          warehouseId: SEED_DATA.WAREHOUSES.SECONDARY,
          binId: SEED_DATA.BINS.SEC_RACK_2,
          quantity: '100', // Received at Secondary
        },
      ],
    },
  ];

  for (const adj of adjustments) {
    const existingAdj = await db.query.inventoryAdjustments.findFirst({
      where: eq(inventoryAdjustments.id, adj.id),
    });

    if (existingAdj) {
      console.log(`   - Adjustment '${adj.reference}' already exists. Skipping.`);
      continue;
    }

    await db.transaction(async (tx) => {
      await tx.insert(inventoryAdjustments).values({
        id: adj.id,
        organizationId: SEED_DATA.ORGANIZATION_ID,
        adjustmentDate: adj.date,
        reason: adj.reason,
        reference: adj.reference,
        status: 'approved',
        createdAt: adj.date,
        updatedAt: adj.date,
        createdBy: SEED_DATA.USER_ID,
        updatedBy: SEED_DATA.USER_ID,
      });

      for (const line of adj.lines) {
        await tx.insert(inventoryAdjustmentLines).values({
          organizationId: SEED_DATA.ORGANIZATION_ID,
          adjustmentId: adj.id,
          productId: line.productId,
          warehouseId: line.warehouseId,
          binId: line.binId,
          quantityChange: line.quantity,
          createdAt: adj.date,
          updatedAt: adj.date,
          createdBy: SEED_DATA.USER_ID,
          updatedBy: SEED_DATA.USER_ID,
        });

        /**
         * ATOMIC UPSERT: We use Postgres ON CONFLICT to ensure that multiple
         * adjustments to the same Bin are additive.
         *
         * SAFETY MEASURE: We employ GREATEST(0, ...) to ensure the check
         * constraint (quantity_on_hand >= 0) is never violated during the
         * initial insert or subsequent updates.
         */
        await tx
          .insert(inventoryLevels)
          .values({
            organizationId: SEED_DATA.ORGANIZATION_ID,
            productId: line.productId,
            warehouseId: line.warehouseId,
            binId: line.binId,
            quantityOnHand: sql`GREATEST(0, ${line.quantity}::numeric)`,
            createdAt: adj.date,
            updatedAt: adj.date,
            createdBy: SEED_DATA.USER_ID,
            updatedBy: SEED_DATA.USER_ID,
          })
          .onConflictDoUpdate({
            target: [
              inventoryLevels.organizationId,
              inventoryLevels.productId,
              inventoryLevels.warehouseId,
              inventoryLevels.binId,
            ],
            set: {
              quantityOnHand: sql`GREATEST(0, ${inventoryLevels.quantityOnHand} + ${line.quantity}::numeric)`,
              updatedAt: adj.date,
              updatedBy: SEED_DATA.USER_ID,
            },
          });

        await tx.insert(inventoryLedgers).values({
          organizationId: SEED_DATA.ORGANIZATION_ID,
          productId: line.productId,
          warehouseId: line.warehouseId,
          binId: line.binId,
          quantityChange: line.quantity,
          referenceType: 'adjustment',
          referenceId: adj.id,
          createdAt: adj.date,
          updatedAt: adj.date,
          createdBy: SEED_DATA.USER_ID,
          updatedBy: SEED_DATA.USER_ID,
        });
      }
    });

    console.log(
      `   - Adjustment '${adj.reference}' created (${adj.date.toISOString().split('T')[0]}).`,
    );
  }
}
